### ISSUE TITLE
Market orders can not be placed

### ISSUE THREAD

**Issue by jkirsteins** [anthonypuppo/GDAXSwift#4]
If I place a market order, I am providing either `price` or `funds`, but not both.

The API call succeeds, but the GDAXOrder parsing code returns `responseParsingFailure("price")`.

This is a sample sandbox response, if I specify size (0.03) and funds 'nil':

`["fill_fees": 0.0000000000000000, "settled": 0, "size": 0.03000000, "type": market, "stp": dc, "product_id": BTC-EUR, "status": pending, "id": a83f8e07-0904-425c-89b7-1192740d66be, "side": buy, "created_at": 2017-12-09T22:54:05.530799Z, "funds": 99750.6234413900000000, "post_only": 0, "executed_value": 0.0000000000000000, "filled_size": 0.00000000]
`

**Comment by anthonypuppo** [comment]
Sorry for the delay in responding to this. Merging your PR.
